splash = false

wallpaper {
    monitor =
    # path = ~/dotfiles/wallpapers/deer.jpg
    path = ~/dotfiles/wallpapers/futurecabin.jpg
    # path = ~/dotfiles/wallpapers/train.png
    # path = ~/dotfiles/wallpapers/wilds.png
    fit_mode = cover
}
